version: '3.8'
services:
  postgres-testing:
    image: postgres:15.0-alpine

    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

    ports:
      - 5432:5432
